site_name: redux-toolkit
site_url: https://austinyu.github.io/redux-toolkit/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: "Switch to light mode"
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: amber
      toggle:
        icon: material/weather-night
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: amber
      toggle:
        icon: material/lightbulb-auto-outline
        name: "Switch to system preference"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow

repo_name: austinyu/redux-toolkit
repo_url: https://github.com/austinyu/redux-toolkit

plugins:
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          inventories:
            - url: https://docs.python.org/3/objects.inv
              domains: [py, std]
  - search

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - Home:
      - Welcome: index.md
      - Quick Start: quick_start.md
      - Contributing: contributing.md
  - API Reference: api.md
  - About:
      - About redux-toolkit: about.md
